apiVersion: v1
kind: Service
metadata:
  name: identity-rs-api
  namespace: sia-services
spec:
  selector:
    sia-app: identity-rs
    tier: api
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-rs
  namespace: sia-services
  labels:
    sia-app: identity-rs
    tier: api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      sia-app: identity-rs
      tier: api
  template:
    metadata:
      labels:
        sia-app: identity-rs
        tier: api
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 1000
      containers:
      - name: main
        image: acc-md.registry.jetbrains.space/p/backend/containers/identity-server-rs:latest
        imagePullPolicy: Always
        env:
        - { name: SERVER_ADDR, value: "0.0.0.0:8443" }
        - { name: "SSL.PATH", value: "/certs" }
        - { name: "SSL.KEYFILE", value: "internal.key" }
        - { name: "SSL.CERTFILE", value: "internal.crt" }
        - { name: "PG.USERNAME", value: "security_service" }
        - { name: "PG.PASSWORD", value: "sec-serv-2022-08-19" }
        - { name: "PG.HOST", value: "10.10.112.11" }
        - { name: "PG.PORT", value: "5432" }
        - { name: "PG.DBNAME", value: "acc" }
        - { name: "PG.MAX_POOL_SIZE", value: "4" }
        ports:
        - containerPort: 8443
        volumeMounts:
        - { name: certs, mountPath: /certs, readOnly: true }
      volumes:
      - { name: certs, secret: { secretName: sia-certs } }
      imagePullSecrets:
      - name: space-reg-credentials
