apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-email-service
  namespace: sia-services
  labels:
    sia-app: send-email-service
    tier: api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      sia-app: send-email-service
      tier: api
  template:
    metadata:
      labels:
        sia-app: send-email-service
        tier: api
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 1000
      containers:
      - name: main
        image: acc-md.registry.jetbrains.space/p/backend/containers/send-email-service:latest
        imagePullPolicy: Always
        env:
        - { name: KEYSTORE_PATH, valueFrom: { configMapKeyRef: { name: quarkus-config, key: keystore_path } } }
        - { name: KEYSTORE_PASSWORD, valueFrom: { secretKeyRef: { name: production-secret, key: keystore-password } } }
        - { name: CLIENT_PASSWORD, valueFrom: { secretKeyRef: { name: production-secret, key: db-client-password } } }
        ports:
        - containerPort: 8443
        volumeMounts:
        - { name: certs, mountPath: /certs, readOnly: true }
      volumes:
      - { name: certs, secret: { secretName: sia-certs } }
      imagePullSecrets:
      - name: space-reg-credentials
